### PR TITLE
only browserify the node dependencies in main.js

### PR DESCRIPTION
**Pull request by edewit**
@jcesarmobile review?

changed the init.js to export the browserified parts to global variables to enable editing with studio preview

### CODE REVIEW

**Comment by jcesarmobile** [comment]
We are using bootstrap CSS, so I think we shouldn't remove bootstrap js.

Other than that it looks good to me.

**Comment by edewit** [comment]
@jcesarmobile isn't bootstrap.js optional? I think you only need it if you use the advanced bootstrap components like the accordion.

**Comment by corinnekrych** [comment]
@edewit tested in
http://testing.client2.skunkhenry.com/#projects/ug6rtintqhn36p4wtf4z56xj/apps/ug6rtin2n4hbzrzq3iv2qutn/editor

preview + live update

**Comment by corinnekrych** [comment]
merged 4860522

**Pull request closed without merging**
